### ISSUE TITLE
启动后报错

### ISSUE THREAD

**Issue by TerrenceFong** [scq000/vue-element-enhanced-table#8]
项目启动后会报错，因为babel没有把node_modules里的es6语法编译为es5的语法
![image](https://user-images.githubusercontent.com/16008881/32366478-3123ca00-c0b9-11e7-8e2a-6dcbc65ef0c0.png)

如果在支持es6的浏览器打开该项目，会提示如下报错
![image](https://user-images.githubusercontent.com/16008881/32366536-791b5724-c0b9-11e7-9ba5-288a9466b2e5.png)

**Comment by scq000** [comment]
这个项目只是做一个参考，如果需要在实际项目中使用请将其移动项目目录中去。
